version: '3.8'

services:
  ali_common_dev:
    build: 
      context: .
      dockerfile: Dockerfile
      args:
        USER_ID: ${USER_ID}
        GROUP_ID: ${GROUP_ID}
    container_name: ali_common_dev_container
    runtime: nvidia
    deploy:
      resources:
        limits:
          cpus: '8'
          memory: 32g
    environment:
      - NVIDIA_VISIBLE_DEVICES=3 
    ports:
      - "2222:22"
      - "8500:8500"
      - "8501:8501"
    volumes:
      - ${HOME}/.gitconfig:/home/user/.gitconfig:ro
      - ${HOME}/sources:/home/user/sources
      - ${HOME}/.cursor-server:/home/user/.cursor-server
      - /media/hdd/ali:/media/hdd/ali
